management:
  cloudfoundry:
    skip-ssl-validation: false
    enabled: true
    endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'