apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-green
  labels:
    app: simple-green
    tier: frontend
spec:
  selector:
    matchLabels:
      app: simple-green
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-green
        tier: frontend
    spec:
      containers:
      - name: simple-green
        image: mayureshkrishna/simple:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80