apiVersion: v1
kind: Service
metadata:
  name: simple
  labels:
    app: simple
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: simple-blue
    tier: frontend
